services:
  nats:
    image: nats:2.10.21
    ports:
      - '4222:4222'
      - '8222:8222'
    command:
      - '--http_port=8222'
      - '--js'
    volumes:
      - nats_data:/data

volumes:
  nats_data:
